GET http://localhost:3000/v1/health HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/v1/post HTTP/1.1
content-type: application/json

{
    "title": "title",
    "content": "content",
    "tags": ["tag1", "tag2"]
}

###
GET http://localhost:3000/v1/post/4 HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3000/v1/post/4 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnb2FwaSIsImV4cCI6MTcyOTg4Mjk1MSwiaWF0IjoxNzI5NjIzNzUxLCJpc3MiOiJnb2FwaSIsIm5iZiI6MTcyOTYyMzc1MSwic3ViIjoxMTZ9.tIXjEuCod4ILGOuqyjJuYuwVb4gVak0QjRBR0UykDyY


###
PATCH http://localhost:3000/v1/post/4 HTTP/1.1
content-type: application/json

{
    "title": "title-updated",
    "content": "content-updated"
}

###
GET http://localhost:3000/v1/user/1 HTTP/1.1
content-type: application/json

###
PUT http://localhost:3000/v1/user/2/follow HTTP/1.1
content-type: application/json

###
PUT http://localhost:3000/v1/user/2/unfollow HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/v1/user/feed?limit=10&offset=0&tags=DIY HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/v1/user/feed?limit=10&offset=0 HTTP/1.1
content-type: application/json

###
POST http://localhost:3000/v1/auth/user HTTP/1.1
content-type: application/json

{
  "email": "testesenha2@mail.com",
  "password": "123456",
  "username": "usernamesenha2"
}

###
@token=
# @name activate_user
PUT http://localhost:3000/v1/user/activate/{{token}} HTTP/1.1

###
# @name login
POST http://localhost:3000/v1/auth/token HTTP/1.1
content-type: application/json

{
  "email": "testesenha2@mail.com",
  "password": "123456"
}